language: csharp

mono: 5.2.0
dotnet: 2.0.0
dist: trusty


install:
  - nuget install xunit.runner.console -version 2.2.0
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi

  # Restore dependencies
  - dotnet restore src/NLog
  - dotnet restore src/NLogAutoLoadExtension

  - dotnet restore tests/SampleExtensions

  - dotnet restore tests/NLog.UnitTests

script:
  # Run tests
  - dotnet test tests/NLog.UnitTests --configuration Release --framework netcoreapp2.0

  - dotnet msbuild /t:Restore /p:targetframework=net452 /p:monobuild=1 src/NLog
  - dotnet msbuild /t:Restore /p:targetframework=net452 /p:monobuild=1 tests/NLog.UnitTests
  - dotnet msbuild /t:Rebuild /p:targetframework=net452 /p:configuration=Release /p:monobuild=1 tests/NLog.UnitTests
  - mono ./xunit.runner.console.2.2.0/tools/xunit.console.exe "./tests/NLog.UnitTests/bin/Release/net452/NLog.UnitTests.dll"
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "osvaldocsouza"
      - git config --local user.email "osvaldoc.souza@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  overwrite: true
  provider: releases
  user: "osvaldocsouza"
  password: "Osv@1985"
  file: "home/travis/build/osvaldocsouza/NLog/src/NLog/bin/Release/net45/NLog.dll"
  skip_cleanup: true
  on:
    tags: true 
    all_branches: true
    rvm: 4.6.90
